- README.md
Hope you can include it, thanks!
Learn more: https://www.taskade.com/blog/introducing-taskade-ai/ and https://www.taskade.com/templates/ai
> added taskade ai

- README.md
Hi, we are the makers of https://www.aipoemgenerator.org, and would love to have it listed under the Text > Services category 🙂
> Add aipoemgenerator.org

- README.md
Please let me know if this is helpful.
> Added BARD

- README.md
Adding Deploy Prompt -service for prompt engineering, to the list
> Add Deploy Prompt to the list

- README.md
Add a description of Nekton.ai service that can automate the text workflow using OpenAI and ChatGPT.
> Add Nekton.ai workflow automaton service

- README.md
Hi, I'd love to add my AI story generator tool to your list 🙂
> Add AI Story Generator

- README.md
> Added PageLines.com

- README.md
Hello @steven2358 
I added my website, which I offer free tools that are powered by AI
Best Regards,
Jon
> Add ZZZ Code AI

- README.md
> Added The AI-Powered Developer

- README.md
Add llamaindex - popular OSS project for building LLM apps over your data. Should satisfy all your criteria but lmk if i'm missing anything 
Github: https://github.com/jerryjliu/llama_index
Twitter: https://twitter.com/llama_index
> Add llamaindex to readme

- README.md
- Adds arize phoenix, an open-source tool for ML observability that runs in your notebook environment. Monitor and fine tune LLM, CV and Tabular Models.
> Add arize-phoenix

- README.md
Add https://github.com/geekan/MetaGPT
> add Code > MetaGPT

- README.md
Include [Colossyan](https://www.colossyan.com/) in the Video section of the list.
> Add Colossyan

- README.md
Add artsmart.ai to the image services list
> Add artsmart.ai to the image services list

- README.md
[**JoliGEN**](https://github.com/jolibrain/joliGEN) is an integrated framework for training custom generative AI image-to-image models
Main Features:
- JoliGEN implements both **GAN and Diffusion models** for unpaired and paired image to image translation tasks, including domain and style adaptation with conservation of semantics such as image and object classes, masks, ...
- JoliGEN generative AI capabilities are targeted at real world applications such as **Controled Image Generation**, **Augmented Reality**, **Dataset Smart Augmentation** and object insertion, **Synthetic to Real** transforms.
> Add joliGEN in Image Services

- README.md
Frameworks, Foundational models, tools for finance focused use cases
> Generative AI 4  Finance focused use cases

- README.md
Morpher AI is a comprehensive tool for market analysis and decision-making. As your personal investment analyst, Morpher AI delivers real-time insights and analysis for any market.
> Add morpher.com/ai to other tools

- README.md
pi.ai is also a great IA, as assistant having an integrated text to speech which acts very fast
> Added pi.ai to the list  !

- README.md
Hello, I've added open source full stack AI voice chatbot to the list. I hope I've picked a proper place, if not please let me know so I can adjust it. Much thanks for maintainting the list!
> Add Gdańsk AI to README.md

- README.md
Added agenta under dev tools. I added it at the beginning seeing that the dev tools are ordered alphabetically. Hope that is alright.
> Added new open-source dev tool (agenta)

- README.md
> Added brokenbear.com an AI teddy bear which you can vent to for free

- DISCOVERIES.md
- README.md
> Stjepanjurekovic patch 3

- README.md
Adds invideo AI in video category
> Update README.md, adds invideo AI

- DISCOVERIES.md
A PR to add [Shotstack Workflows](https://shotstack.io/product/workflows/) to the list. For consideration. Thank you.
> Add Shotstack Workflows

- README.md
Add Deliberative Prompting list.
> Add deliberative prompting list

- README.md
> Added AI-Assisted Testing

- README.md
> Added Automate Everyday Tasks with ChatGPT Plus

- README.md
> Added Build a Large Language Model (From Scratch)

- README.md
added ludwig 
Signed-off-by: Jason Poley [jason.poley@gmail.com](mailto:jason.poley@gmail.com)
> added ludwig

- DISCOVERIES.md
- README.md
> Added Introduction to Generative AI

- DISCOVERIES.md
- README.md
> Added Generative AI in Action

- DISCOVERIES.md
- README.md
Added to coding section 👊
More info - https://www.blackbox.ai/about
> Added Blackbox AI

- DISCOVERIES.md
- README.md
Added Pixee to Coding > Developer tools. 
Pixeebot finds security and code quality issues in your code and creates merge-ready pull requests with recommended fixes.
> Added Pixee

- README.md
[Plandex](https://github.com/plandex-ai/plandex) is an open source, terminal-based AI programming engine for complex tasks.
> Add Plandex
